### ISSUE TITLE
[Egg Request]: CockroachDB

### ISSUE THREAD

**Issue by BasToTheMax** [pelican-eggs/eggs#1987]
### Does this expand an already existing service

No

### Link to a game or software

https://github.com/cockroachdb/cockroach

### Links for the download

https://binaries.cockroachdb.com/cockroach-v22.1.11.linux-amd64.tgz

### Links for the install docs

https://www.cockroachlabs.com/docs/stable/install-cockroachdb-linux.html

**Comment by cyteon** [comment]
bump

**Comment by gOOvER** [comment]
https://github.com/pelican-eggs/eggs/blob/master/README.md
