### ISSUE TITLE
[Bug]: Arma Reforger curl timeout (fix found and validated)

### ISSUE THREAD

**Issue by BrokenGearsTV** [pelican-eggs/eggs#2879]
### Panel Version

1.1.15

### Wings Version

1.1.11

### Service

Arma Reforger

### Modified

No, I did not modify the egg

### Expected Behavior

Install server, add mods on the config file restart server starts

### Actual Behavior

Same problem as in https://github.com/parkervcp/eggs/issues/2783
You closed it but problem lies with arma workshop needing a /tmp folder configured.
This has been verified by Arma Reforger developers

![image](https://github.com/parkervcp/eggs/assets/48889543/21da53c4-6852-48f0-854d-dd8de110ebbf)
-addonTempDir with a directory needs to be added to launch parameters and it will fix the problem.

Has been confirmed by all my clients.

### Steps To Reproduce

Install server
Add mod in config
error

add -addonTempDir
restart server
mod downloads fine

### Install logs

https://pteropaste.com/6ngpo2n8ew6i/

**Comment by BrokenGearsTV** [comment]
https://pterodactyl.io/wings/1.0/configuration.html#other-values
Can be fixed by increasing tmpfs_size for the specific node.

**Comment by danny6167** [comment]
Makes sense. The default `/tmp/` that gets mounted into the container is very small

**Comment by parkervcp** [comment]
I think a better fix is to have this be part of the start command so I am keeping it open. I can look at this later today when I have time.

**Comment by lilkingjr1** [comment]
I wonder if SteamCMD also uses the OS `/tmp/` folder for certain things, which may be why large Workshop downloads fail?... Probably not because it has it's own cache folder within the container volume, but still...
