### ISSUE TITLE
[Bug]: Bastion

### ISSUE THREAD

**Issue by IkyMax** [pelican-eggs/eggs#2886]
### Panel Version

1.11.5

### Wings Version

1.11.11

### Service

Discord Bot

### Modified

No, I did not modify the egg

### Expected Behavior

Run

### Actual Behavior

> bastion@10.15.0 start
> node .
node:internal/modules/cjs/loader:451
      throw err;
      ^
Error: Cannot find module '/home/container/dist/index.js'. Please verify that the package.json has a valid "main" entry
    at tryPackage (node:internal/modules/cjs/loader:443:19)
    at Module._findPath (node:internal/modules/cjs/loader:714:18)
    at resolveMainPath (node:internal/modules/run_main:26:23)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:128:24)
    at node:internal/main/run_main_module:28:49 {
  code: 'MODULE_NOT_FOUND',
  path: '/home/container/package.json',
  requestPath: '/home/container'
}
Node.js v20.12.1
Error parsing command line: unrecognised option '--eval'

### Steps To Reproduce

Install latest version

### Install logs

https://pteropaste.com/i1pdw0khb3r4

**Comment by ImKringle** [comment]
<--- JS stacktrace --->

FATAL ERROR: Ineffective mark-compacts near heap limit Allocation failed - JavaScript heap out of memory
----- Native stack trace -----
Your bot ran out of memory - try allocating more RAM to the container. Also that pteropaste has your bot token, change that like now lol

**Comment by IkyMax** [comment]
on it lol, btw, it cant literally be without ram, it doesnt even have a ram limit XD

**Comment by ImKringle** [comment]
> on it lol, btw, it cant literally be without ram, it doesnt even have a ram limit XD

Better to set a RAM limit as well

**Comment by QuintenQVD0** [comment]
> <--- JS stacktrace --->
> 
> FATAL ERROR: Ineffective mark-compacts near heap limit Allocation failed - JavaScript heap out of memory ----- Native stack trace ----- Your bot ran out of memory - try allocating more RAM to the container. Also that pteropaste has your bot token, change that like now lol

0 is unlimeted for the game container. But 1000mb for the instalk container.

**Comment by IkyMax** [comment]
oh ok, thx!

**Comment by QuintenQVD0** [comment]
> oh ok, thx!

it works now for you? so we can close this.
