### ISSUE TITLE
Minecraft Bedrock Proxy

### ISSUE THREAD

**Issue by GabBiswajit** [pelican-eggs/eggs#2889]
### Does this expand an already existing service

Yes

### Link to a game or software

https://github.com/Paroxity/portal?tab=readme-ov-file

### Links for the download

https://github.com/Paroxity/portal/releases/

### Links for the install docs

https://github.com/Paroxity/portal/blob/master/README.md

**Comment by parkervcp** [comment]
The same comment I generally have about minecraft being that new ones pop up all the time. Closing this out while we also move to the new category layout.

See https://github.com/orgs/pelican-eggs/repositories
