### ISSUE TITLE
[Egg Request]: Movie-Web

### ISSUE THREAD

**Issue by zf-development** [pelican-eggs/eggs#2907]
### Does this expand an already existing service

No

### Link to a game or software

https://github.com/movie-web

### Links for the download

https://github.com/orgs/movie-web/packages

### Links for the install docs

https://movie-web.github.io/docs/

**Comment by Brolofmeistertv** [comment]
+1

**Comment by sys-arch** [comment]
@zf-development Check links. None of them works.

**Comment by QuintenQVD0** [comment]
The linked software does not seem to exist (anymore) so I am closing this.
