### ISSUE TITLE
[Bug]: mongodb connection  error

### ISSUE THREAD

**Issue by satyampandeygithub** [pelican-eggs/eggs#2916]
### Panel Version

1.11.5

### Wings Version

1.11.11

### Service

https://github.com/pelican-eggs/eggs/tree/master/database/nosql/mongodb

### Modified

no

### Expected Behavior

it shall work , i should be able to connect to my project

### Actual Behavior

it didnt connects, gives out refused error while connecting from mongodb compass

### Steps To Reproduce

the error i receive while restarting my server is
"error":{"code":9001,"codeName":"SocketException","errmsg":"socket exception [CONNECT_ERROR] server [couldn't connect to server 127.0.0.1:5678, connection attempt failed: SocketException: Error connecting to 127.0.0.1:5678 :: caused by :: Connection refused]"}}}
container@pterodactyl~ Server marked as offline...
idk why is this happening ive tried sudo ufw allow

### Install logs

https://pteropaste.com/qact/

**Comment by QuintenQVD0** [comment]
Could you please try the mongodb 6 or 7 egg? as 4 and 5 are EOL.

Also this is known to not working on unraid or proxmox.

**Comment by satyampandeygithub** [comment]
works as a charm now, but what are the causes of it? @QuintenQVD0

**Comment by satyampandeygithub** [comment]
also i have files of my old mongodb server, its mongodb 7 too would it work if i copy paste files?

**Comment by QuintenQVD0** [comment]
> also i have files of my old mongodb server, its mongodb 7 too would it work if i copy paste files?

you should be able to import them using a mongodb connect application

**Comment by QuintenQVD0** [comment]
> works as a charm now, but what are the causes of it? @QuintenQVD0

binoic been EOL, same with mongodb 4 and 5, they just droped support. 
No idea wy it has this issue.

**Comment by satyampandeygithub** [comment]
actually, the vps i use was full on its storage so i decided to reset it. as it was not able to handle requests so i just copied those files using ftp now im getting error when i uploaded those files, 
nc: connect to 127.0.0.1 port 5678 (tcp) failed: Connection refused
Waiting for mongodb connection...

**Comment by QuintenQVD0** [comment]
> actually, the vps i use was full on its storage so i decided to reset it. as it was not able to handle requests so i just copied those files using ftp now im getting error when i uploaded those files, nc: connect to 127.0.0.1 port 5678 (tcp) failed: Connection refused Waiting for mongodb connection...

my guess is you toched or changed files that should not be touched.

**Comment by gOOvER** [comment]
> actually, the vps i use was full on its storage so i decided to reset it. as it was not able to handle requests so i just copied those files using ftp now im getting error when i uploaded those files, nc: connect to 127.0.0.1 port 5678 (tcp) failed: Connection refused Waiting for mongodb connection...

you cant simply copy and paste mongodb Files.

**Comment by satyampandeygithub** [comment]
ah understood, but what shall i do now? i dont wala loose my data i was not able to backup it from mongodb compass.

**Comment by QuintenQVD0** [comment]
At this point it is not an egg issue anymore, please consult the mongodb documentation.
