### ISSUE TITLE
[Install Bug]: tModLoader

### ISSUE THREAD

**Issue by TheTrueColonel** [pelican-eggs/eggs#2922]
### Panel Version

1.11.5

### Wings Version

1.11.11

### Service

terraria/tmodloader

### Modified

No, I did not modify the egg

### Expected Behavior

Install the server, it installs correctly and can run.

### Actual Behavior

Server crashed giving the following errors:

```
dotnet --version
6.0.421
:/home/container$ ./tModLoaderServer -ip 0.0.0.0 -port ${SERVER_PORT} -maxplayers ${MAX_PLAYERS} -password "${SERVER_PASSWORD}" -motd "${MOTD}" -lang ${LANGUAGE} -world ~/saves/Worlds/${WORLD_NAME}.wld -worldname ${WORLD_NAME} -autocreate ${WORLD_SIZE} -config serverconfig.txt -savedirectory ~/ -tmlsavedirectory ~/saves -modpath ~/mods
You must install or update .NET to run this application.
App: /home/container/tModLoader.dll
Architecture: x64
Framework: 'Microsoft.NETCore.App', version '8.0.0' (x64)
.NET location: /usr/share/
The following frameworks were found:
  6.0.29 at [/usr/share/shared/Microsoft.NETCore.App]
Learn about framework resolution:
https://aka.ms/dotnet/app-launch-failed
To install missing framework, download:
https://aka.ms/dotnet-core-applaunch?framework=Microsoft.NETCore.App&framework_version=8.0.0&arch=x64&rid=debian.12-x64
```

### Steps To Reproduce

1. Start the server with the latest version of egg
2. Watch server install
3. Server fails to launch

### Install logs

https://pteropaste.com/n23d/

**Comment by ImKringle** [comment]
#2914 You need dotnet8, set your image on the server to `ghcr.io/parkervcp/yolks:dotnet_8`

**Comment by QuintenQVD0** [comment]
This repo is not used anymore and will no longer accept any PR.

This issue has been fixt in the new split up repo [Here](https://github.com/pelican-eggs/games/tree/main/terraria/tmodloader)
