### ISSUE TITLE
[Egg Request]: FOUNDRY dedicated server request

### ISSUE THREAD

**Issue by kkoshelev** [pelican-eggs/eggs#2925]
### Does this expand an already existing service

No

### Link to a game or software

https://www.foundry-game.com/

### Links for the download

https://steamdb.info/app/2915550/depots/

### Links for the install docs

https://dedicated.foundry-game.com/

**Comment by sampsi** [comment]
+1

**Comment by IngoMitDingo** [comment]
+1

**Comment by kkoshelev** [comment]
Almost made it work. The server  crashed on startup. Maybe someone can fix it

[egg-foundry.json](https://github.com/pelican-eggs/eggs/files/15195359/egg-foundry.json)

**Comment by Liborsaf** [comment]
> Almost made it work. The server crashed on startup. Maybe someone can fix it
> 
> [egg-foundry.json](https://github.com/pelican-eggs/eggs/files/15195359/egg-foundry.json)

From log started with WINEDEBUG="+timestamp,+pid,+tid,+seh,+debugstr,+module"

```
145748.059:013c:0140:err:winediag:nodrv_CreateWindow Application tried to create a window, but no driver could be loaded.
145748.059:013c:0140:err:winediag:nodrv_CreateWindow L"Make sure that your X server is running and that $DISPLAY is set correctly."
```

I did some tests with it, and it seems like this could be the problem maybe? 🤔 
It probably tries to open new window as console, instead of just using normal i/o.

But this is just my guess 😄

**Comment by QuintenQVD0** [comment]
I will make it work, but do not use that egg for now as startup script is user editable and bad for security

**Comment by gOOvER** [comment]
> I will make it work, but do not use that egg for now as startup script is user editable and bad for security.
> 
> This also looks a litte liek a goover egg with the colors.

the dev do not share any infos. I tryied it allread. ATM its not possible to create an server

**Comment by gOOvER** [comment]
> Almost made it work. The server crashed on startup. Maybe someone can fix it
> 
> [egg-foundry.json](https://github.com/pelican-eggs/eggs/files/15195359/egg-foundry.json)

proton run  .\/FoundryDedicatedServerLauncher.bat",

Start scripts are not alloowed and not needed

**Comment by gOOvER** [comment]
> > Almost made it work. The server crashed on startup. Maybe someone can fix it
> > [egg-foundry.json](https://github.com/pelican-eggs/eggs/files/15195359/egg-foundry.json)
> 
> From log started with WINEDEBUG="+timestamp,+pid,+tid,+seh,+debugstr,+module"
> 
> ```
> 145748.059:013c:0140:err:winediag:nodrv_CreateWindow Application tried to create a window, but no driver could be loaded.
> 145748.059:013c:0140:err:winediag:nodrv_CreateWindow L"Make sure that your X server is running and that $DISPLAY is set correctly."
> ```
> 
> I did some tests with it, and it seems like this could be the problem maybe? 🤔 It probably tries to open new window as console, instead of just using normal i/o.
> 
> But this is just my guess 😄

thats the problem. No server needs a Window, so i bet, the egg dont work :D

Allready reported that issue to the devs, but Foundry devs hate the public

**Comment by kkoshelev** [comment]
> proton run ./FoundryDedicatedServerLauncher.bat",
> Start scripts are not allowed and not needed

Yeah, that was a quick attempt to use their script in case that would fix the problem, it didn't. Anyhow, I'm glad that I got enough attention for this to get the work going.

**Comment by kkoshelev** [comment]
> Sry, but the egg in this state do not work

Can you help to make it work? Someone made it work in docker with wine and x-server, see [link](https://github.com/luxusburg/docker-foundry/blob/main/Dockerfile).

**Comment by ImKringle** [comment]
Works fine with Wine from what my own server shows (Cant share for cause its from work, soz), Proton though no chance; @gOOvER using your image itll boot (kinda) but on connection it just auto crashes so its wine or nothing lol

**Comment by Liborsaf** [comment]
> > Sry, but the egg in this state do not work
> 
> Can you help to make it work? Someone made it work in docker with wine and x-server, see [link](https://github.com/luxusburg/docker-foundry/blob/main/Dockerfile).

With wine and -log in arguments, it seems to be working fine for me 🥳

Here is my modified egg file: [egg-foundry.json](https://github.com/pelican-eggs/eggs/files/15205296/egg-foundry.json)

**Comment by Kaofan1** [comment]
> > > Sry, but the egg in this state do not work
> > 
> > 
> > Can you help to make it work? Someone made it work in docker with wine and x-server, see [link](https://github.com/luxusburg/docker-foundry/blob/main/Dockerfile).
> 
> With wine and -log in arguments, it seems to be working fine for me 🥳
> 
> Here is my modified egg file: [egg-foundry.json](https://github.com/pelican-eggs/eggs/files/15205296/egg-foundry.json)

Well, actually, you managed to do it because it works well

**Comment by Kaofan1** [comment]
@Liborsaf 

I just don't understand why there is "Proton" when "Wine" works great

**Comment by Liborsaf** [comment]
> @Liborsaf
> 
> I just don't understand why there is "Proton" when "Wine" works great

Hmm, I tried to get Proton working but without success. Does it work for you just by switching Docker image to Proton and startup parameters or how?

**Comment by kkoshelev** [comment]
>it seems to be working fine for me
Thank you for making it work!

Small change in done condition, needed to change the server ready string, here is the final version [egg-foundry.json](https://github.com/pelican-eggs/eggs/files/15205731/egg-foundry.json). Tested, it works great.

@gOOvER would you please create a PR for this, I'm sure many people would be happy.

**Comment by Liborsaf** [comment]
Just few minor things, I removed the Proton from egg for now and added creation of Mods folder to install script.

Egg: [egg-foundry.json](https://github.com/pelican-eggs/eggs/files/15208271/egg-foundry.json)

**Comment by gOOvER** [comment]
> > it seems to be working fine for me
> 
> Thank you for making it work!
> 
> Small change in done condition, needed to change the server ready string, here is the final version [egg-foundry.json](https://github.com/pelican-eggs/eggs/files/15205731/egg-foundry.json). Tested, it works great.
> 
> @gOOvER would you please create a PR for this, I'm sure many people would be happy.

i can commit my egg, but it needs some rewrites

**Comment by Kaofan1** [comment]
> > > it seems to be working fine for me
> > 
> > 
> > Thank you for making it work!
> > Small change in done condition, needed to change the server ready string, here is the final version [egg-foundry.json](https://github.com/pelican-eggs/eggs/files/15205731/egg-foundry.json). Tested, it works great.
> > @gOOvER would you please create a PR for this, I'm sure many people would be happy.
> 
> i can commit my egg, but it needs some rewrites
> 
> Edit: you can test this. If it works for you, i will rewrite it for PelicanPanel, becasue i use other variables.
> 
> https://github.com/gOOvER/own-pterodactyl-eggs/tree/main/steamcmd/foundry

Works well too

**Comment by HerrSammyDE** [comment]
Are there any updates on the game yet?
I haven't been able to test it yet, but I will soon.

**Comment by QuintenQVD0** [comment]
was added here: https://github.com/pelican-eggs/steamcmd/pull/6

**Comment by HerrSammyDE** [comment]
Doesn't Foundry have an auto update?
@gOOvER @QuintenQVD0

**Comment by gOOvER** [comment]
> Doesn't Foundry have an auto update? @gOOvER @QuintenQVD0

it should :P

I fix that tomorrow
