### ISSUE TITLE
[Egg Request]:  Abiotic Factor

### ISSUE THREAD

**Issue by ValhallaCommunityOfficial** [pelican-eggs/eggs#2926]
### Does this expand an already existing service

No

### Link to a game or software

https://store.steampowered.com/app/427410/Abiotic_Factor/

### Links for the download

https://steamdb.info/app/2857200/

### Links for the install docs

https://github.com/DFJacob/AbioticFactorDedicatedServer/wiki/Guide-%E2%80%90-Quickstart

**Comment by ValhallaCommunityOfficial** [comment]
Awesome! Thanks you, egg works great

**Comment by Truyn** [comment]
> Потрясающий! Спасибо, яйцо работает отлично



> Awesome! Thank you, egg works great

How to download it?

**Comment by RStivanson** [comment]
> How to download it?

It's not currently merged yet, but you can visit the [PR here](https://github.com/pelican-eggs/steamcmd/pull/4) and grab the egg from the `Files changed` tab.
