### ISSUE TITLE
[Egg Request]: Foundry

### ISSUE THREAD

**Issue by TheG33kDev** [pelican-eggs/eggs#2932]
### Does this expand an already existing service

Yes

### Link to a game or software

https://www.paradoxinteractive.com/games/foundry/about

### Links for the download

Steam

### Links for the install docs

https://dedicated.foundry-game.com

**Comment by RStivanson** [comment]
Added here https://github.com/pelican-eggs/steamcmd/pull/6

**Comment by QuintenQVD0** [comment]
This repo is not used anymore. And indeed. Added to the new steamcme repo.
