### ISSUE TITLE
LinkStack egg suggestion

### ISSUE THREAD

**Issue by GabrieleYT9768** [pelican-eggs/eggs#2937]
### Does this expand an already existing service

Yes

### Link to a game or software

https://linkstack.org/

### Links for the download

https://github.com/linkstackorg/linkstack/releases/latest/download/linkstack.zip

### Links for the install docs

https://linkstack.org/docker/

**Comment by GabrieleYT9768** [comment]
This is really useful as a self-hosted alternative to linktr.ee

**Comment by gOOvER** [comment]
needs apache2 and php, wo nothing for an agg
